# Hyprland configuration overrides
# Add your custom settings here

# Example overrides:
# $mainMod = SUPER

# Autostart
#exec-once = uwsm-app -- hyprsunset
exec-once = hyprctl setcursor Bibata-Modern-Ice 24

# Keybindings
unbind = SUPER SHIFT, G
unbind = SUPER SHIFT, W
unbind = SUPER SHIFT, SLASH
unbind = SUPER SHIFT ALT, A
unbind = SUPER SHIFT, C
unbind = SUPER SHIFT, E
unbind = SUPER SHIFT, Y
unbind = SUPER SHIFT ALT, G
unbind = SUPER SHIFT CTRL, G
unbind = SUPER SHIFT, P
unbind = SUPER SHIFT, X, X
unbind = SUPER SHIFT ALT, X
unbind = SUPER ALT, SPACE # Omarchy Menu
unbind = SUPER CTRL, SPACE # Next background in theme
unbind = SUPER ALT, F # Full width
unbind = SUPER CTRL, F # Tiled full screen
unbind = SUPER CTRL, X, # Start dictation
unbind = SUPER CTRL, X, # Stop dictation
unbind = SUPER, T, # Toggle window floating/tiling
unbind = SUPER CTRL, TAB, # Former workspace
unbind = SUPER SHIFT ALT, LEFT # Move workspace to left monitor
unbind = SUPER SHIFT ALT, RIGHT # Move workspace to right monitor
unbind = SUPER SHIFT ALT, UP # Move workspace to up monitor
unbind = SUPER SHIFT ALT, DOWN # Move workspace to down monitor
unbind = SUPER CTRL, LEFT # Move grouped window focus left
unbind = SUPER CTRL, RIGHT # Move grouped window focus right

bindd = SUPER CTRL, SPACE, Omarchy menu, exec, omarchy-menu
bindd = SUPER CTRL, F, Full width, fullscreen, 1

# Resize active window
# bindd = SUPER, minus, Expand window left, resizeactive, -100 0    # - key
# bindd = SUPER, equal, Shrink window left, resizeactive, 100 0     # = key
# bindd = SUPER SHIFT, minus, Shrink window up, resizeactive, 0 -100
# bindd = SUPER SHIFT, equal, Expand window down, resizeactive, 0 100

general {
    gaps_in = 3
    gaps_out = 5

    border_size = 1
}

input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  kb_layout = latam
  # kb_layout = us
  # kb_options = grp:alt_shift_toggle
  kb_options = grep:caps_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  touchpad {
    scroll_factor = 0.4
  }
}

decoration {
    rounding = 10
    rounding_power = 1
    active_opacity = 1.0
    inactive_opacity = 0.8
    fullscreen_opacity = 1.0

    blur {
        enabled = true
        size = 10
        passes = 2
        new_optimizations = on
        ignore_opacity = true
        xray = true
        contrast = 2
    }
}

# Monitors
monitor = DP-2, 1920x1080@144, 0x0,    auto
monitor = DP-1, 1920x1080@60,  1920x0, auto

cursor {
    hide_on_key_press = false
    # default_monitor = DP-2
}
